# Generated by Django 4.0.4 on 2022-08-23 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbearia', models.CharField(max_length=200, verbose_name='Barbearia')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('logo', stdimage.models.StdImageField(blank=True, null=True, upload_to='barbearia/logo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(help_text='Ex: Barba - Cabelo - Bigode', max_length=100, verbose_name='Serviço')),
                ('tempo', models.CharField(choices=[('30', '30 Minutos'), ('60', '01 Hora')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='profissionais')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('descricao', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='produtos')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_da_semana', models.CharField(choices=[('Segunda a Sexta', 'Segunda a Sexta'), ('Segunda a Sábado', 'Segunda a Sábado'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-freira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16)),
                ('horario_inicio', models.CharField(max_length=5, verbose_name='Horário Início')),
                ('horario_saida', models.CharField(max_length=5, verbose_name='Horário Saída')),
                ('inicio_intervalo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Início Intervalo')),
                ('final_intervalo', models.CharField(blank=True, max_length=5, null=True, verbose_name='Final Intervalo')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(blank=True, max_length=16, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('inscricao', models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rua', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rua')),
                ('numero', models.CharField(blank=True, max_length=5, null=True, verbose_name='N°')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cidade')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('numero', models.CharField(max_length=5, verbose_name='N°')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('barbearia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_created=True, auto_now_add=True)),
                ('conta', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataVencimento', models.DateField()),
                ('infoPago', models.CharField(max_length=10)),
                ('pago', models.BooleanField(default=False)),
                ('vencido', models.BooleanField(default=False)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_created=True, auto_now_add=True)),
                ('conta', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dataVencimento', models.DateField()),
                ('infoPago', models.CharField(max_length=10)),
                ('pago', models.BooleanField(default=False)),
                ('vencido', models.BooleanField(default=False)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_created=True, auto_now_add=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='AgendaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('horarioFim', models.TimeField()),
                ('agendado', models.BooleanField(default=True)),
                ('antendido', models.BooleanField(default=False)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.clientes')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.profissionais')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.servicos')),
            ],
            options={
                'verbose_name': 'Agenda Horario',
                'verbose_name_plural': 'Agenda Horarios',
            },
        ),
    ]
