# Generated by Django 4.0.4 on 2022-04-29 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbearia', models.CharField(max_length=200, verbose_name='Barbearia')),
                ('nome', models.CharField(help_text='Informe aqui seu nome completo.', max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.CharField(help_text='Ex: Barba - Cabelo - Bigode', max_length=100, verbose_name='Nome do Serviço')),
                ('tempo', models.CharField(choices=[('15', '15 Minutos'), ('30', '30 Minutos'), ('01', '01 Hora')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Preço(R$)')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_da_semana', models.CharField(choices=[('Todos os dias', 'Todos os dias'), ('Segunda a Sexta', 'Segunda a Sexta'), ('Segunda a Sábado', 'Segunda a Sábado'), ('Segunda Feira', 'Segunda Feira'), ('Terça Feira', 'Terça Feira'), ('Quarta Feira', 'Quarta Freira'), ('Quinta Feira', 'Quinta Feira'), ('Sexta Feira', 'Sexta Feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16)),
                ('horario_inicio', models.TimeField(help_text='Ex "00:00"', verbose_name='Horário Início')),
                ('horario_saida', models.TimeField(help_text='Ex "00:00"', verbose_name='Horário Saída')),
                ('inicio_intervalo', models.TimeField(help_text='Ex "00:00"', verbose_name='Início Intervalo')),
                ('final_intervalo', models.TimeField(help_text='Ex "00:00"', verbose_name='Final Intervalo')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Horário de Atendimento',
                'verbose_name_plural': 'Horários de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua')),
                ('numero', models.CharField(max_length=5, verbose_name='N°')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
