# Generated by Django 4.0.4 on 2022-06-29 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbearias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia'),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.clientes'),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.profissionais'),
        ),
        migrations.AddField(
            model_name='agendahorario',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.servicos'),
        ),
    ]
