# Generated by Django 4.0.4 on 2022-05-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite aqui seu nome completo', max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
