# Generated by Django 4.0.4 on 2022-05-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='dias_da_semana',
            field=models.CharField(choices=[('Todos os dias', 'Todos os dias'), ('Segunda a Sexta', 'Segunda a Sexta'), ('Segunda a Sábado', 'Segunda a Sábado'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-freira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='final_intervalo',
            field=models.CharField(blank=True, help_text='Ex "00:00"', max_length=5, null=True, verbose_name='Final Intervalo'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='horario_inicio',
            field=models.CharField(help_text='Ex "00:00"', max_length=5, verbose_name='Horário Início'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='horario_saida',
            field=models.CharField(help_text='Ex "00:00"', max_length=5, verbose_name='Horário Saída'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='inicio_intervalo',
            field=models.CharField(blank=True, help_text='Ex "00:00"', max_length=5, null=True, verbose_name='Início Intervalo'),
        ),
    ]
