# Generated by Django 4.0.4 on 2022-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0003_profissionais_bairro_profissionais_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendahorario',
            name='agendado',
            field=models.BooleanField(default=True),
        ),
    ]
