# Generated by Django 4.0.4 on 2022-08-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0004_alter_agendahorario_agendado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionais',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='rua',
        ),
    ]
