# Generated by Django 4.0.4 on 2022-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0004_alter_horariofuncionamento_final_intervalo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='final_intervalo',
            field=models.CharField(blank=True, default='--', help_text='Ex "00:00"', max_length=5, null=True, verbose_name='Final Intervalo'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='inicio_intervalo',
            field=models.CharField(blank=True, default='--', help_text='Ex "00:00"', max_length=5, null=True, verbose_name='Início Intervalo'),
        ),
    ]
