# Generated by Django 4.0.4 on 2022-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0005_remove_profissionais_bairro_remove_profissionais_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendahorario',
            name='horarioFim',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='tempo',
            field=models.CharField(choices=[('30', '30 Minutos'), ('60', '01 Hora')], max_length=2),
        ),
    ]
