# Generated by Django 4.0.4 on 2022-08-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0006_agendahorario_horariofim_alter_servicos_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendahorario',
            name='horarioFim',
            field=models.TimeField(),
        ),
    ]
