# Generated by Django 4.0.4 on 2022-05-13 18:02

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0007_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='barbearia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
