# Generated by Django 4.0.4 on 2022-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0009_alter_agendahorario_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendahorario',
            name='horarioFim',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
