# Generated by Django 4.0.4 on 2022-05-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0010_alter_agendahorario_options_agendahorario_agendado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servicos',
            field=models.CharField(blank=True, help_text='Ex: Barba - Cabelo - Bigode', max_length=100, null=True, verbose_name='Nome do Serviço'),
        ),
    ]
