# Generated by Django 4.0.4 on 2022-08-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0011_alter_agendahorario_horariofim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendahorario',
            name='horarioFim',
        ),
    ]
