# Generated by Django 4.0.4 on 2022-06-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0013_alter_clientes_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='dias_da_semana',
            field=models.CharField(choices=[('Todos os dias', 'Todos os dias'), ('Segunda a Sexta', 'Segunda a Sexta'), ('Segunda a Sábado', 'Segunda a Sábado'), ('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-freira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16),
        ),
    ]
