# Generated by Django 4.0.4 on 2022-06-17 13:39

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0015_alter_horariofuncionamento_final_intervalo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='profissionais',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Profissionais'),
        ),
    ]
