# Generated by Django 4.0.4 on 2022-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0018_alter_horariofuncionamento_final_intervalo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='final_intervalo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='horario_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='horario_saida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='inicio_intervalo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
