# Generated by Django 4.0.4 on 2022-06-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0020_alter_horariofuncionamento_final_intervalo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCadastro', models.DateField(auto_created=True)),
                ('conta', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dataVencimento', models.DateField()),
                ('pago', models.BooleanField(default=False)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia')),
            ],
        ),
    ]
