# Generated by Django 4.0.4 on 2022-06-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0021_alter_barbearia_nome_contapagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
    ]
