# Generated by Django 4.0.4 on 2022-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0022_alter_contapagar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='infoPago',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='dataCadastro',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
