# Generated by Django 4.0.4 on 2022-06-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0024_alter_contapagar_valor_contareceber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
    ]
