# Generated by Django 4.0.4 on 2022-06-27 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0025_contapagar_vencido_contareceber_vencido'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dataCadastro',
            field=models.DateField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
